name: build kernel
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Step 2: Set up dependencies
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi python3
      # Step 3: Run the build script
      - name: Build Kernel
        run: |
          cd kernel-5.10
          python3 scripts/gen_build_config.py \
            --kernel-defconfig a24_00_defconfig \
            --kernel-defconfig-overlays entry_level.config \
            -m user \
            -o ../out/target/product/a24/obj/KERNEL_OBJ/build.config
          export ARCH=arm64
          export PLATFORM_VERSION=13
          export CROSS_COMPILE="aarch64-linux-gnu-"
          export CROSS_COMPILE_COMPAT="arm-linux-gnueabi-"
          export OUT_DIR="../out/target/product/a24/obj/KERNEL_OBJ"
          export DIST_DIR="../out/target/product/a24/obj/KERNEL_OBJ"
          export BUILD_CONFIG="../out/target/product/a24/obj/KERNEL_OBJ/build.config"
          cd ../kernel
          ./build/build.sh
      # Step 4: Upload build artifacts (optional)
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: out/target/product/a24/obj/KERNEL_OBJ/
